### ISSUE TITLE
Autoplay Feature

### ISSUE THREAD

**Issue by irchriscott** [jama5262/CarouselView#14]
**It would be better if there was an auto-play feature.**
Sometimes, people want to see dynamic carousel where new items are showing without their interaction.

**Comment by jama5262** [comment]
Hi @irchriscott , thanks for the contribution. I understand this is a wanted feature. I will work on it as soon as possible 👍

**Comment by jama5262** [comment]
@irchriscott https://github.com/jama5262/CarouselView/releases
