### ISSUE TITLE
Cant add the CaruselView

### ISSUE THREAD

**Issue by galgistmd** [jama5262/CarouselView#17]
Hi, I'm getting an error while trying to implement the library. I have added maven....

> ERROR: Failed to resolve: com.github.jama5262:CarouselView:1.1.0
Show in Project Structure dialog
Affected Modules: app

**Comment by jama5262** [comment]
Hi @galgistmd have you added jitpack to build.gradle?

```
allprojects {
    repositories {
        ...
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by galgistmd** [comment]
Hi, yes I did.
I also tried to do a research about the problem with no success.

**Comment by jama5262** [comment]
@galgistmd Can you try this StackOverflow answer and reply the results
https://stackoverflow.com/a/37892027/6459510

**Comment by galgistmd** [comment]
Thank you very much for your reply,
problem solved,
Have a nice day.
