### ISSUE TITLE
scroll to position by index

### ISSUE THREAD

**Issue by galgistmd** [jama5262/CarouselView#18]
Hi, Is there a possibility to add a function that auto scrolls to a specified index ?
It will be very helpful, (that also disables scrolling).
thanks.

**Comment by jama5262** [comment]
Hi @galgistmd, yes you can scroll to a specific item, by just setting the `currentItem`  to the index position you want. But as for disabling the scroll, not yet implemented

**Comment by galgistmd** [comment]
Hi, I'm trying to figure out the `currentItem` func. unfortunately when you insert the index of the item (based 0) it doesn't work. In order for it to work you need to enter the real position (based 1).
sometimes it works and sometimes not.
can you check it yourself please ?

king regards,
thank you.

**Comment by jama5262** [comment]
Closed this issue, related to this issue #19
